### ISSUE TITLE
ModuleNotFoundError: No module named 'FaceEngine'

### ISSUE THREAD

**Issue by WuZhuoran** [matemax/lunasdk#34]
After install the package with `pip install`.

When I try to run the demo usage, the following error occurred:

```python
from lunavl.sdk.luna_faces import VLFaceDetector
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/lunavl/sdk/luna_faces.py", line 5, in <module>
    from FaceEngine import Face  # pylint: disable=E0611,E0401
ModuleNotFoundError: No module named 'FaceEngine'
```

**Comment by matemax** [comment]
Hi. There are dependencies that imposible install through the pip unfortunately.

>The main dependencies is Luna SDK library and an FaceEnginePythonBindings. 

You should connect with visionlabs for getting the dependencies (https://visionlabs.ai).
